######################################################################
# Automatically generated by qmake (3.0) Wed Apr 29 12:32:05 2020
######################################################################

TEMPLATE = app
TARGET = UI
INCLUDEPATH += .

# Input
HEADERS += ui.h
SOURCES += main.cpp ui.cpp
QT += core gui widgets
